"""DDL idempotente nos dois dialetos + versao de dados (para SSE/cache).

Diferencas por dialeto sao resolvidas por substituicao de tokens:
  {PK_AUTO}  id autogerado (rowid no SQLite, IDENTITY no Postgres)
  {BLOB}     bytes (BLOB / BYTEA)
Datas/horas ficam como TEXT ISO-8601 UTC nos dois bancos (consistencia total
com o codigo ja testado; ordenacao lexicografica == cronologica).
"""
from __future__ import annotations

from .connection import Db

SCHEMA_VERSION = 3  # v3: users.bio (descrição do perfil)

_DIALECT_TOKENS = {
    "sqlite": {
        "PK_AUTO": "INTEGER PRIMARY KEY",
        "PK_PLAIN": "INTEGER PRIMARY KEY",
        "BLOB": "BLOB",
    },
    "postgres": {
        "PK_AUTO": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "PK_PLAIN": "BIGINT PRIMARY KEY",
        "BLOB": "BYTEA",
    },
}

DDL_TEMPLATE = """
CREATE TABLE IF NOT EXISTS users (
  id {PK_AUTO},
  email TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  password_hash TEXT,
  google_sub TEXT UNIQUE,
  avatar_ver INTEGER NOT NULL DEFAULT 0,
  bio TEXT,
  is_admin INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS refresh_tokens (
  jti TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  revoked_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rt_user ON refresh_tokens(user_id);
CREATE TABLE IF NOT EXISTS teams (
  id {PK_AUTO},
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  flag TEXT NOT NULL,
  group_letter TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS matches (
  id {PK_PLAIN},
  stage TEXT NOT NULL,
  group_letter TEXT,
  kickoff_utc TEXT NOT NULL,
  venue TEXT NOT NULL,
  home_source TEXT NOT NULL,
  away_source TEXT NOT NULL,
  home_team_id BIGINT REFERENCES teams(id),
  away_team_id BIGINT REFERENCES teams(id),
  home_score INTEGER,
  away_score INTEGER,
  status TEXT NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled','live','finished')),
  minute INTEGER,
  winner_team_id BIGINT REFERENCES teams(id),
  manual_lock INTEGER NOT NULL DEFAULT 0,
  external_id TEXT,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_matches_status ON matches(status);
CREATE INDEX IF NOT EXISTS idx_matches_kickoff ON matches(kickoff_utc);
CREATE TABLE IF NOT EXISTS bets (
  id {PK_AUTO},
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  home_goals INTEGER NOT NULL CHECK (home_goals BETWEEN 0 AND 20),
  away_goals INTEGER NOT NULL CHECK (away_goals BETWEEN 0 AND 20),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (user_id, match_id)
);
CREATE INDEX IF NOT EXISTS idx_bets_match ON bets(match_id);
CREATE INDEX IF NOT EXISTS idx_bets_user ON bets(user_id);
CREATE TABLE IF NOT EXISTS avatars (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  data {BLOB} NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
)
"""


def render_ddl(dialect: str) -> str:
    tokens = _DIALECT_TOKENS[dialect]  # dialeto desconhecido = bug: KeyError
    ddl = DDL_TEMPLATE
    for token, value in tokens.items():
        ddl = ddl.replace("{" + token + "}", value)
    return ddl


# PRAGMA não aceita parâmetro; whitelist literal (sem interpolação) p/ passar
# o scanner anti-injeção de SQL.
_TABLE_INFO = {"users": "PRAGMA table_info(users)"}


def _column_exists(db: Db, table: str, column: str) -> bool:
    if db.dialect == "sqlite":
        rows = db.execute(_TABLE_INFO[table]).fetchall()
        return any(r["name"] == column for r in rows)
    rows = db.execute(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = ? AND column_name = ?",
        (table, column),
    ).fetchall()
    return len(rows) > 0


def _migrate(db: Db) -> None:
    """Migrações idempotentes p/ DBs já existentes (cross-dialeto)."""
    if not _column_exists(db, "users", "bio"):
        db.execute("ALTER TABLE users ADD COLUMN bio TEXT")


def init_db(db: Db) -> None:
    db.executescript(render_ddl(db.dialect))
    _migrate(db)
    db.execute(
        "INSERT INTO meta (key, value) VALUES ('data_version', '0') "
        "ON CONFLICT (key) DO NOTHING"
    )
    db.execute(
        "INSERT INTO meta (key, value) VALUES ('users_version', '0') "
        "ON CONFLICT (key) DO NOTHING"
    )
    db.execute(
        "INSERT INTO meta (key, value) VALUES ('schema_version', ?) "
        "ON CONFLICT (key) DO NOTHING",
        (str(SCHEMA_VERSION),),
    )


def get_data_version(db: Db) -> int:
    row = db.execute("SELECT value FROM meta WHERE key = 'data_version'").fetchone()
    return int(row["value"]) if row else 0


def bump_data_version(db: Db) -> int:
    db.execute(
        "UPDATE meta SET value = CAST(CAST(value AS INTEGER) + 1 AS TEXT) "
        "WHERE key = 'data_version'"
    )
    return get_data_version(db)


def get_users_version(db: Db) -> int:
    """Versao do ESTADO de usuarios (membership/nome/avatar). Invalida caches
    que dependem de usuarios (ex.: leaderboard), independente de data_version."""
    row = db.execute("SELECT value FROM meta WHERE key = 'users_version'").fetchone()
    return int(row["value"]) if row else 0


def bump_users_version(db: Db) -> int:
    db.execute(
        "UPDATE meta SET value = CAST(CAST(value AS INTEGER) + 1 AS TEXT) "
        "WHERE key = 'users_version'"
    )
    return get_users_version(db)
